{% set name = "pymks" %}
{% set version = "0.3.3.dev20+g050b7a8" %}
{% set github_org = "wd15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ github_org }}/{{ name }}.git
  git_rev: 050b7a8

build:
  number: 1

requirements:
  build:
    - python
    - anaconda
    - pytest
    - scikit-learn
    - pytest-cov
    - pylint
    - cython
    - sympy
    - pytables
    - configparser

  run:
    - python
    - anaconda
    - pytest
    - scikit-learn
    - pytest-cov
    - pylint
    - cython
    - sympy
    - pytables
    - pyparsing
    - matplotlib
    - configparser

about:
  home: http://{{ name }}.org
