---
package:
  name: pymks
  version: "0.3.1"

source:
  git_url: https://github.com/materialsinnovation/pymks.git
  git_rev: a3757c72

build:
  number: 1

requirements:
  build:
    - python
    - anaconda
    - sfepy
    - pytest
    - scikit-learn

  run:
    - python
    - anaconda
    - sfepy
    - pytest
    - scikit-learn

about:
  home: http://pymks.org
