{% set version = "2016.3" %}
{% set name = "sfepy" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ name }}/{{ name }}.git
  git_rev: release_{{ version }}

build:
  number: 1

requirements:
  build:
    - python
    - anaconda
    - cython
    - sympy
    - pytables

  run:
    - python
    - anaconda
    - pyparsing
    - sympy
    - cython
    - pytables

about:
  home: http://{{ name }}.org
